const cloudinary = require("cloudinary").v2;

function cloudUp(filename) {
  const eager_options = {
    width: 200,
    height: 133,
    crop: "scale",
    format: "jpg"
  };

  cloudinary.uploader
    .upload(filename, {
      public_id: filename.slice(0, -4),
      eager: eager_options
    })
    .then(function(err, image) {
      console.log("upload");
      console.log(
        "* public_id for the uploaded image is generated by Cloudinary's service."
      );
      console.log("* " + image.public_id);
      console.log("* " + image.url);
    })
    .catch(function(err) {
      if (err) {
        console.warn(err);
      }
    });
}
